---
apiVersion: v1
kind: Service
metadata:
  name: msrjdbc
  annotations:
  labels:
    name: msrjdbc
spec:
  type: LoadBalancer
  ports:
  - port: 5555
    targetPort: 5555
  selector:
    app: msrjdbc

