apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: contract-management
  name: contract-management
spec:
  replicas: 1 
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  minReadySeconds: 60
  selector:
    matchLabels:
      app: contract-management
  template:
    metadata:
      labels:
        app: contract-management
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: contract-management-microgateway
        image: staillansag/contract-management:mcgw-0.0.1
        imagePullPolicy: Always
        env:
        - name: mcgw_api_gateway_url
          value: https://env262868.apigw-aw-eu.webmethods.io
        - name: mcgw_api_gateway_user
          value: admin
        - name: mcgw_api_gateway_password
          valueFrom:
            secretKeyRef:
              name: apigw-secret
              key: password
        - name: mcgw_downloads_apis
          value: Insurance_contract-management
        - name: mcgw_ports_http
          value: "9090"
        - name: mcgw_ports_https
          value: "9093"
        - name: mcgw_microgatewayPool_microgatewayPoolName
          value: contract-management-mcgw
        - name: mggw_applications_sync_enabled
          value: "true"
        - name: mggw_applications_sync_polling_interval_secs
          value: "10"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/softwareag/Microgateway/files/k8s-lifenesscheck.sh
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/softwareag/Microgateway/files/k8s-readinesscheck.sh
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      - image: staillansag/contract-management:0.0.3
        imagePullPolicy: Always
        name: contract-management-microservice
        env:
        - name: SAG_IS_CONFIG_PROPERTIES
          value: /opt/softwareag/IntegrationServer/contract-management.properties
        - name: PARTY_URL
          value: https://party-management:443/gateway/Insurance_party-management/1.0
        - name: PARTY_KEY
          value: ddf249c2-181a-491b-8cea-5e9b9e1e02ff
        resources:
          limits:
            cpu: 500m
            memory: 800Mi
        ports:
        - containerPort: 5555

