<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getUserName</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWxhc3ROYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJsYXN0TmFtZSIgKTsNCglTdHJpbmcJZmlyc3ROYW1lID0gSURhdGFVdGlsLmdldFN0
cmluZyggcGlwZWxpbmVDdXJzb3IsICJmaXJzdE5hbWUiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0
cm95KCk7DQoJCQ0KU3RyaW5nIHVzZXJOYW1lID0gTm9ybWFsaXplci5ub3JtYWxpemUoZmlyc3RO
YW1lICsgIi4iICsgbGFzdE5hbWUsIE5vcm1hbGl6ZXIuRm9ybS5ORkQpDQoucmVwbGFjZUFsbCgi
W15cXHB7QVNDSUl9XSIsICIiKS50b0xvd2VyQ2FzZSgpOw0KDQovLyBwaXBlbGluZQ0KSURhdGFD
dXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGls
LnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInVzZXJOYW1lIiwgdXNlck5hbWUgKTsNCnBpcGVsaW5l
Q3Vyc29yXzEuZGVzdHJveSgpOw0KDQoJ</value>
</Values>
